service: serverless-nestjs

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
